#!/bin/sh

# THIS WILL OVERWRITE ~/.zshrc, ~/.vimrc


# force link dotfiles
ln -sf ~/.dotfiles/zsh/.zshrc ~/.zshrc
ln -sf ~/.dotfiles/vim/.vimrc ~/.vimrc

# force link *.zsh files to $ZSH/custom to be loaded by oh-my-zsh
for f in zsh/*.zsh
do
  ln -sf ~/.dotfiles/"$f" "$ZSH"/custom/"$(basename ${f})"
done

# make sure all plugins pulled in from .gitmodules are present
git submodule update --init

# delete and rsync custom zsh plugins to $ZSH/custom/plugins
rm -rf "$ZSH"/custom/plugins/*
rsync -a zsh/plugins/ "$ZSH"/custom/plugins
