#!/usr/bin/env zsh
#
# Maintainer: jdbargas
#
# links up dotfiles, custom zsh files, and custom zsh plugins

# test if arguments were passed
if [ $# -eq 0 ]
then
  # display message about what will be overwritten if run with 'force'
  echo "***************************************"
  echo "**** THIS IS A DESTRUCTIVE COMMAND ****"
  echo "***************************************\n"
  echo "!!! if any of these files/folders exist, they will be overwritten !!!\n"
  echo "to be overwritten in ~/"
  echo "~/.zshrc"
  echo "~/.vimrc"
  echo ""
  echo "to be overwritten in "$ZSH"/custom/"
  (cd zsh && ls -1 *.zsh)
  echo ""
  echo "to be overwritten in "$ZSH"/custom/plugins/"
  (cd "$ZSH"/custom/plugins/ && ls -d1 */)
  echo ""
  echo "to be overwritten in "$ZSH"/custom/themes/"
  (cd "$ZSH"/custom/themes/ && ls -1)
  echo ""
  echo "if you wish to proceed, rerun with 'force' argument"
  exit 1
fi

# get args now that we know something is there
FORCE_FLAG=$1

if [ "$FORCE_FLAG" = "force" ]
then
  # force link dotfiles
  echo "linking ~/.zshrc"
  echo "linking ~/.vimrc"
  echo ""
  ln -sf ~/.dotfiles/zsh/.zshrc ~/.zshrc
  ln -sf ~/.dotfiles/vim/.vimrc ~/.vimrc

  # force link *.zsh files to $ZSH/custom to be loaded by oh-my-zsh
  for f in zsh/*.zsh
  do
    echo "linking "$ZSH"/custom/"$(basename ${f})""
    ln -sf ~/.dotfiles/"$f" "$ZSH"/custom/"$(basename ${f})"
  done
  echo ""

  # make sure all plugins pulled in from .gitmodules are present
  git submodule update --init

  # force link plugins directory
  ln -sf ~/.dotfiles/zsh/plugins/ "$ZSH"/custom/plugins
  echo "zsh plugins:\n"
  (cd zsh/plugins && ls -d1 */)
  echo ""

  # force link themes directory
  ln -sf ~/.dotfiles/zsh/themes/ "$ZSH"/custom/themes 
  echo "zsh themes:\n"
  (cd zsh/themes && ls -1)
  echo ""
  echo "finished linking. run 'omz reload' for settings to take effect."
else
  # if something other than 'force' is passed, display friendly error message
  echo "argument '"$1"' is not recognized. exiting."
fi
